### ISSUE TITLE
dynamic linking ODP to DPDK 20.11

### ISSUE THREAD

**Issue by Carisbrooke** [OpenDataPlane/odp-dpdk#117]
Hi,

Thanks for the patches, ODP-DPDK now successfully compiles with DPDK 20.11. However its statically linking against it e.g.

 ./configure --disable-static-applications --enable-static=no

creates the following output from configure:

        dependency libs:        -lconfig -lcrypto -Wl,-L/usr/local/lib,--whole-archive,-l:librte_common_cpt.a,-l:librte_common_dpaax.a,-l:librte_common_iavf.a,-l:librte_common_octeontx.a,-l:librte_common_octeontx2.a,-l:librte_common_sfc_efx.a,-l:librte_bus_dpaa.a,-l:librte_bus_fslmc.a,-l:librte_bus_ifpga.a,-l:librte_bus_pci.a,-l:librte_bus_vdev.a,-l:librte_bus_vmbus.a,-l:librte_common_mlx5.a,-l:librte_common_qat.a,-l:librte_mempool_bucket.a,-l:librte_mempool_dpaa.a,-l:librte_mempool_dpaa2.a,-l:librte_mempool_octeontx.a,-l:librte_mempool_octeontx2.a,-l:librte_mempool_ring.a,-l:librte_mempool_stack.a,-l:librte_net_af_packet.a,-l:librte_net_ark.a,-l:librte_net_atlantic.a,-l:librte_net_avp.a,-l:librte_net_axgbe.a,-l:librte_net_bond.a,-l:librte_net_bnx2x.a,-l:librte_net_bnxt.a,-l:librte_net_cxgbe.a,-l:librte_net_dpaa.a,-l:librte_net_dpaa2.a,-l:librte_net_e1000.a,-l:librte_net_ena.a,-l:librte_net_enetc.a,-l:librte_net_enic.a,-l:librte_net_failsafe.a,-l:librte_net_fm10k.a,-l:librte_net_i40e.a,-l:librte_net_hinic.a,-l:librte_net_hns3.a,-l:librte_net_iavf.a,-l:librte_net_ice.a,-l:librte_net_igc.a,-l:librte_net_ipn3ke.a,-l:librte_net_ixgbe.a,-l:librte_net_kni.a,-l:librte_net_liquidio.a,-l:librte_net_memif.a,-l:librte_net_mlx4.a,-l:librte_net_mlx5.a,-l:librte_net_netvsc.a,-l:librte_net_nfp.a,-l:librte_net_null.a,-l:librte_net_octeontx.a,-l:librte_net_octeontx2.a,-l:librte_net_pcap.a,-l:librte_net_pfe.a,-l:librte_net_qede.a,-l:librte_net_ring.a,-l:librte_net_sfc.a,-l:librte_net_softnic.a,-l:librte_net_tap.a,-l:librte_net_thunderx.a,-l:librte_net_txgbe.a,-l:librte_net_vdev_netvsc.a,-l:librte_net_vhost.a,-l:librte_net_virtio.a,-l:librte_net_vmxnet3.a,-l:librte_raw_dpaa2_cmdif.a,-l:librte_raw_dpaa2_qdma.a,-l:librte_raw_ifpga.a,-l:librte_raw_ioat.a,-l:librte_raw_ntb.a,-l:librte_raw_octeontx2_dma.a,-l:librte_raw_octeontx2_ep.a,-l:librte_raw_skeleton.a,-l:librte_crypto_aesni_gcm.a,-l:librte_crypto_aesni_mb.a,-l:librte_crypto_bcmfs.a,-l:librte_crypto_caam_jr.a,-l:librte_crypto_ccp.a,-l:librte_crypto_dpaa_sec.a,-l:librte_crypto_dpaa2_sec.a,-l:librte_crypto_kasumi.a,-l:librte_crypto_nitrox.a,-l:librte_crypto_null.a,-l:librte_crypto_octeontx.a,-l:librte_crypto_octeontx2.a,-l:librte_crypto_openssl.a,-l:librte_crypto_scheduler.a,-l:librte_crypto_snow3g.a,-l:librte_crypto_virtio.a,-l:librte_crypto_zuc.a,-l:librte_compress_isal.a,-l:librte_compress_octeontx.a,-l:librte_compress_zlib.a,-l:librte_regex_mlx5.a,-l:librte_regex_octeontx2.a,-l:librte_vdpa_ifc.a,-l:librte_vdpa_mlx5.a,-l:librte_event_dlb.a,-l:librte_event_dlb2.a,-l:librte_event_dpaa.a,-l:librte_event_dpaa2.a,-l:librte_event_octeontx2.a,-l:librte_event_opdl.a,-l:librte_event_skeleton.a,-l:librte_event_sw.a,-l:librte_event_dsw.a,-l:librte_event_octeontx.a,-l:librte_baseband_null.a,-l:librte_baseband_turbo_sw.a,-l:librte_baseband_fpga_lte_fec.a,-l:librte_baseband_fpga_5gnr_fec.a,-l:librte_baseband_acc100.a,-l:librte_node.a,-l:librte_graph.a,-l:librte_bpf.a,-l:librte_flow_classify.a,-l:librte_pipeline.a,-l:librte_table.a,-l:librte_port.a,-l:librte_fib.a,-l:librte_ipsec.a,-l:librte_vhost.a,-l:librte_stack.a,-l:librte_security.a,-l:librte_sched.a,-l:librte_reorder.a,-l:librte_rib.a,-l:librte_regexdev.a,-l:librte_rawdev.a,-l:librte_pdump.a,-l:librte_power.a,-l:librte_member.a,-l:librte_lpm.a,-l:librte_latencystats.a,-l:librte_kni.a,-l:librte_jobstats.a,-l:librte_ip_frag.a,-l:librte_gso.a,-l:librte_gro.a,-l:librte_eventdev.a,-l:librte_efd.a,-l:librte_distributor.a,-l:librte_cryptodev.a,-l:librte_compressdev.a,-l:librte_cfgfile.a,-l:librte_bitratestats.a,-l:librte_bbdev.a,-l:librte_acl.a,-l:librte_timer.a,-l:librte_hash.a,-l:librte_metrics.a,-l:librte_cmdline.a,-l:librte_pci.a,-l:librte_ethdev.a,-l:librte_meter.a,-l:librte_net.a,-l:librte_mbuf.a,-l:librte_mempool.a,-l:librte_rcu.a,-l:librte_ring.a,-l:librte_eal.a,-l:librte_telemetry.a,-l:librte_kvargs.a,--no-whole-archive,-lIPSec_MB,/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/librt.so,-lmlx5,-lpthread,-lcrypto,-ldl,-lpthread,-lmlx4,-lpthread,-libverbs,-lbnxt_re-rdmav25,-lcxgb4-rdmav25,-lefa,-lhns-rdmav25,-li40iw-rdmav25,-lmlx4,-lmlx5,-lmthca-rdmav25,-locrdma-rdmav25,-lqedr-rdmav25,-lvmw_pvrdma-rdmav25,-lhfi1verbs-rdmav25,-lipathverbs-rdmav25,-lrxe-rdmav25,-lsiw-rdmav25,-libverbs,-lpthread,-lnl-route-3,-lnl-3,-lpcap,-lisal,-lelf,-lz,--as-needed,-lrte_node,-lrte_graph,-lrte_bpf,-lrte_flow_classify,-lrte_pipeline,-lrte_table,-lrte_port,-lrte_fib,-lrte_ipsec,-lrte_vhost,-lrte_stack,-lrte_security,-lrte_sched,-lrte_reorder,-lrte_rib,-lrte_regexdev,-lrte_rawdev,-lrte_pdump,-lrte_power,-lrte_member,-lrte_lpm,-lrte_latencystats,-lrte_kni,-lrte_jobstats,-lrte_ip_frag,-lrte_gso,-lrte_gro,-lrte_eventdev,-lrte_efd,-lrte_distributor,-lrte_cryptodev,-lrte_compressdev,-lrte_cfgfile,-lrte_bitratestats,-lrte_bbdev,-lrte_acl,-lrte_timer,-lrte_hash,-lrte_metrics,-lrte_cmdline,-lrte_pci,-lrte_ethdev,-lrte_meter,-lrte_net,-lrte_mbuf,-lrte_mempool,-lrte_rcu,-lrte_ring,-lrte_eal,-lrte_telemetry,-lrte_kvargs,-lpthread,-lm,-ldl,-lnuma,-lfdt,-lpcap

Is it possible to dynamically link to DPDK?

**Comment by matiaselo** [comment]
Thanks for reporting this. We'll look into this while improving the overall DPDK 20.11 support. DPDK linking can be tricky due to the the driver constructors.

**Comment by Carisbrooke** [comment]
Thanks, I'll also have a look and if successful provide patches.

**Comment by matiaselo** [comment]
FYI there is a work-in-progress experimental patch here: https://github.com/matiaselo/odp-dpdk/commit/553d275dce040ce16ac6202e75cc95263cba1638. It's still quite "hacky" and does not work yet on all platforms.

**Comment by Carisbrooke** [comment]
Hi, many thanks. Appears to be compiling okay, however guessing that ODP doesn't "pull in" the PMDs so no NICs etc are found.

/usr/local/bin/odp_hello
EAL: Detected 16 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'VA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: No legacy callbacks, legacy socket not created
Pool config:
  pool.pkt.max_num: 262143

Queue config:
  queue_basic.max_queue_size: 8191
  queue_basic.default_queue_size: 4095

Using scheduler 'basic'
Scheduler config:
  sched_basic.prio_spread: 4
  sched_basic.prio_spread_weight: 63
  sched_basic.burst_size_default[] =  32  32  32  32  32  16   8   4
  sched_basic.burst_size_max[] =     255 255 255 255 255  16  16   8
  sched_basic.group_enable.all: 1
  sched_basic.group_enable.worker: 1
  sched_basic.group_enable.control: 1

Packet IO config:
  pktio.pktin_frame_offset: 0

PKTIO: initialized null interface.
No crypto devices available
odp_pool.c:746:odp_pool_create():Cannot init DPDK mbuf pool: No such file or directory
../linux-generic/odp_ipsec_events.c:50:_odp_ipsec_events_init_global():Error: status pool create failed.
odp_init.c:497:odp_init_global():ODP IPsec events init failed.

and

ldd /usr/local/bin/odp_hello
        linux-vdso.so.1 (0x00007ffdba2b8000)
        libodp-dpdk.so.125 => /usr/local/lib/libodp-dpdk.so.125 (0x000014cace0bf000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x000014cacdecd000)
        libatomic.so.1 => /lib/x86_64-linux-gnu/libatomic.so.1 (0x000014cacdec3000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x000014cacdbed000)
        libconfig.so.9 => /lib/x86_64-linux-gnu/libconfig.so.9 (0x000014cacdbdf000)
        librte_eventdev.so.21 => /usr/local/lib/librte_eventdev.so.21 (0x000014cacdbb5000)
        librte_cryptodev.so.21 => /usr/local/lib/librte_cryptodev.so.21 (0x000014cacdba1000)
        librte_timer.so.21 => /usr/local/lib/librte_timer.so.21 (0x000014cacdb9a000)
        librte_ethdev.so.21 => /usr/local/lib/librte_ethdev.so.21 (0x000014cacdaf1000)
        librte_mbuf.so.21 => /usr/local/lib/librte_mbuf.so.21 (0x000014cacdae4000)
        librte_mempool.so.21 => /usr/local/lib/librte_mempool.so.21 (0x000014cacdad8000)
        librte_ring.so.21 => /usr/local/lib/librte_ring.so.21 (0x000014cacdad3000)
        librte_eal.so.21 => /usr/local/lib/librte_eal.so.21 (0x000014cacd9db000)
        librte_net_ring.so.21 => /usr/local/lib/librte_net_ring.so.21 (0x000014cacd9d1000)
        librte_bus_vdev.so.21 => /usr/local/lib/librte_bus_vdev.so.21 (0x000014cacd9ca000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x000014cacd9a7000)
        /lib64/ld-linux-x86-64.so.2 (0x000014cace196000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x000014cacd9a1000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x000014cacd850000)
        libnuma.so.1 => /lib/x86_64-linux-gnu/libnuma.so.1 (0x000014cacd843000)
        libfdt.so.1 => /lib/x86_64-linux-gnu/libfdt.so.1 (0x000014cacd838000)
        librte_kvargs.so.21 => /usr/local/lib/librte_kvargs.so.21 (0x000014cacd833000)
        librte_telemetry.so.21 => /usr/local/lib/librte_telemetry.so.21 (0x000014cacd828000)
        librte_net.so.21 => /usr/local/lib/librte_net.so.21 (0x000014cacd81e000)
        librte_meter.so.21 => /usr/local/lib/librte_meter.so.21 (0x000014cacd817000)
        librte_hash.so.21 => /usr/local/lib/librte_hash.so.21 (0x000014cacd802000)
        librte_rcu.so.21 => /usr/local/lib/librte_rcu.so.21 (0x000014cacd7fb000)
        librte_bus_pci.so.21 => /usr/local/lib/librte_bus_pci.so.21 (0x000014cacd7eb000)
        librte_pci.so.21 => /usr/local/lib/librte_pci.so.21 (0x000014cacd7e4000)

**Comment by matiaselo** [comment]
Hi,

What configuration options did you use to build DPDK and ODP-DPDK?

The patch is working on my local system with DPDK build:
```
meson configure -Dprefix=<dpdk_install_path>
meson configure -Ddefault_library=shared
```

And ODP-DPDK:
`PKG_CONFIG_PATH=<dpdk_install_path>/lib/x86_64-linux-gnu/pkgconfig ./configure --disable-static --enable-dpdk-shared`

**Comment by Carisbrooke** [comment]
Just tried it on my LX2160A ARM based machine and everything works correctly (using the built-in NIC). My original X86 test box is using Mellanox NICs they have additional external dependencies (libmlx5.so &  libibverbs.so). So maybe something specific to them.
