### ISSUE TITLE
ODP Timers starting on control threads don't 'fire'

### ISSUE THREAD

**Issue by bogdanPricope** [OpenDataPlane/odp-dpdk#119]
I am using ODP-DPDK (linux-dpdk platform) v1.24.0.0 on a x64 setup.
2 cores running control threads
N cores running workers (odp_schedule_multi())

What I see is that the timers starting on control threads/cores are not 'firing' - don't generate ODP_EVENT_TIMEOUT events.
If I am starting the same timers on a worker core I can see the ODP_EVENT_TIMEOUT events.

Is that a scheduler or a timer feature?

**Comment by matiaselo** [comment]
Hi Bogdan,

That is a feature of the DPDK timer implementation. The normal rte_timer_manage() function processes only timers which were set by that particular thread.

There is also a new alternative timer implementation rte_timer_alt, which enables processing timers globally. In DPKD v20.11 the API is not marked as experimental anymore, so we could actually start using it.

**Comment by bogdanPricope** [comment]
Hi Matias,

Thank you for the information.

I understand that the alternative solution is to use (for now) the linux-generic platform (dpdk pktio), right?

**Comment by matiaselo** [comment]
> I understand that the alternative solution is to use (for now) the linux-generic platform (dpdk pktio), right?

That one or you could modify the application code, so that the control threads also call `odp_schedule()`, which will trigger timer processing.

**Comment by bogdanPricope** [comment]
> That one or you could modify the application code, so that the control threads also call odp_schedule(), which will trigger timer processing.

That will be outside the design. 

Merci and  best regards.
