### ISSUE TITLE
Multicast receive not enabled on linux-generic/dpdk pktio

### ISSUE THREAD

**Issue by bogdanPricope** [OpenDataPlane/odp-dpdk#138]
ODP-DPDK v1.25.2.0, platform linux-generic

Multicast receive is not enable on linux-generic platform/dpdk pktio.

Please add a rte_eth_allmulticast_enable() around dpdk_open() in platform/linux-generic/pktio/dpdk.c.

Merci.

**Comment by MatiasElo** [comment]
Hi,

Good catch. This change should be done to the ODP linux-generic repo, so the issue should also be moved there.

**Comment by MatiasElo** [comment]
Here's a commit which should fix the issue: https://github.com/MatiasElo/odp/commit/4ed37f47c9bbd5fded9278c40a20d38562f98e44

It would be good to still move the issue to linux-gen, so I can reference it in the commit message.

**Comment by bogdanPricope** [comment]
Hi Matias,

I've added the issue on linuc-generic repo: https://github.com/OpenDataPlane/odp/issues/1326

Thank you.
