### ISSUE TITLE
Set of all_bits of odp_pktin_hash_proto_t doesn't has effect. 

### ISSUE THREAD

**Issue by rivasiv** [OpenDataPlane/odp-dpdk#155]
Hi, 

	/** All bits of the bit field structure */
	uint32_t all_bits;
} odp_pktin_hash_proto_t;

Set of all_bits of odp_pktin_hash_proto_t doesn't has effect. Shouldn't it enable all the bits in odp_pktin_hash_proto_t struct proto  ?

**Comment by rivasiv** [comment]
My fault.

**Comment by MatiasElo** [comment]
No problem. Based on this issue I actually posted a small API clarification PR https://github.com/OpenDataPlane/odp/pull/1387.
