### ISSUE TITLE
Alternate DPDK timer implementation

### ISSUE THREAD

**Issue by bogdanPricope** [OpenDataPlane/odp-dpdk#163]
Why is the 'alternate timer implementation' not the main timer implementation, in order to have the same behavior as for 'linux-generic' platform?
I mean, any platform implementation should replicate the behavior of 'linux-generic' that is the reference implementation, or..?

**Comment by MatiasElo** [comment]
The motivation was to avoid changes for the current applications (potential performance hit due to shared resources). Also, for DPDK v19.11 alternate timer was still marked as experimental.
