### ISSUE TITLE
'configure' error with platform linux-generic

### ISSUE THREAD

**Issue by bogdanPricope** [OpenDataPlane/odp-dpdk#170]
odp-dpdk v1.32.0.0_DPDK_19.11

Command:
./configure --with-dpdk-path=YYY --prefix=XXX--enable-dpdk-zero-copy --with-platform=linux-generic

Error:
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).

Cause as printed in config.log
config.status:1945: cd platform/linux-dpdk       && sed -e '/# am--include-marker/d' Makefile         | make -f - am--depfiles
/tmp/GmkyFgTq:2451: ../../platform/linux-generic/Makefile.inc: No such file or directory
make: *** No rule to make target '../../platform/linux-generic/Makefile.inc'.  Stop.

It seems you are missing a 'platform/linux-generic/Makefile.inc' file. If I add an empty file the configure succeeds.

**Comment by MatiasElo** [comment]
Hi Bogdan,

Interesting, we are building linux-generic in the CI with Ubuntu 18.04 and everything is working there. However, I was able to reproduce the issue on my local 20.04 server. The following change fixed the issue for me:
```
diff --git a/platform/linux-dpdk/Makefile.am b/platform/linux-dpdk/Makefile.am
index bd2ce4e8d..da1775993 100644
--- a/platform/linux-dpdk/Makefile.am
+++ b/platform/linux-dpdk/Makefile.am
@@ -1,5 +1,7 @@
 include $(top_srcdir)/platform/Makefile.inc
+if PLATFORM_IS_LINUX_DPDK
 include $(top_srcdir)/platform/@with_platform@/Makefile.inc
+endif
 lib_LTLIBRARIES += $(LIB)/libodp-dpdk.la
 
 AM_CPPFLAGS  =  $(ODP_INCLUDES)
```

I'll try to figure out a cleaner solution next week.

**Comment by bogdanPricope** [comment]
Hi Matias,

I can confirm you that this issue was noticed on Ubuntu 20.04.3 LTS.

Best regards
