### ISSUE TITLE
ODP scheduler(s) performance characterization

### ISSUE THREAD

**Issue by bogdanPricope** [OpenDataPlane/odp-dpdk#172]
Hi Matias,

Did you have the performance characterization numbers for the different ODP schedulers?

I am doing an IP fwd test with the packets received in scheduler mode (default scheduler), ODP_SCHED_SYNC_ATOMIC, multiple input queues (one per worker), RSS, UDP with a large variation of src/dest ports. Running the same scenario multiple times and with different number of cores I am getting a lot of variation of packet rate (mpps).

 1 core					|  1.35 |  1.35 |  1.35
 2 cores					|  6.36 |  3.13 |  3.03 |  2.17 | 6.03 | 3.14 |   3.12
 3 cores					| 13.52 | 13.86 | 13.87 | 13.86
 4 cores					|  5.95 |  5.91 | 14.28 | 14.29 | 5.92

What I am seeing is a very unequal load on the cores. e.g on a 4 workers tests I have:
Thread   Core        ODP_to_FP        FP_to_ODP

      6      1        113640137        113640130
      8      2         24545858         24545858
      9      3        116978523        116978523
     10      4        114715385        114715385
I suspect the scheduler is doing some weird stuff...

**Comment by MatiasElo** [comment]
Hi Bogdan,

From the different scheduler implementations the basic scheduler should perform the best in most scenarios. I suspect the unbalance you are seeing is caused by the priority level spread optimization of the basic scheduler. You can tweak the scheduler options in the config file (`config/odp-linux-dpdk.conf`) under `sched_basic` section.

Assuming you have enough queues for each worker and the traffic is evenly distributed into these queues, the best performance can usually be achieved by setting the `prio_spread` option to the number of worker threads.

**Comment by bogdanPricope** [comment]
Hi Matias,

That did not helped.

I have this ODP configuration file (that I set with ODP_CONFIG_FILE)

$ cat odp_perf.conf
odp_implementation = "linux-generic"
config_file_version = "0.1.18"

sched_basic: {
	prio_spread = 4
}
The sched settings:
Using scheduler 'basic'
Scheduler config:
  sched_basic.prio_spread: 4
  sched_basic.prio_spread_weight: 63
  sched_basic.load_balance: 1
  sched_basic.burst_size_default[] =  32  32  32  32  32  16   8   4
  sched_basic.burst_size_max[] =     255 255 255 255 255  16  16   8
  sched_basic.group_enable.all: 1
  sched_basic.group_enable.worker: 1
  sched_basic.group_enable.control: 1
  dynamic load balance: ON

The throughput observed in consecutive runs: 4 cores: 4 prio_spread: 10.13 | 10.08 | 5.94 | 5.92 | 10.91 | 5.91 | 14.30
Core 2 is still unbalanced when I see lower throughput.
 Thread   Core        ODP_to_FP        FP_to_ODP

      6      1        160032735        158615180
      8      2         35663853         35348299
      9      3        165384325        163935036
     10      4        161928941        160508181

Though, nice pattern when running with 6 cores...
      7      1        112825635        112825635
      8      2         69379762         69379762
      9      3         10617653         10617653
     10      4         10396431         10396431
     11      5         66714327         66714326
     12      6        120829128        120829112

**Comment by MatiasElo** [comment]
The priority spread option makes threads prefer some of the queues over others. So, if there is a relatively low number of queues and some queues have less traffic, a phenomenon like you are seeing may happen. You can see the queue mappings from `odp_schedule_print()` output (should be called after all threads have started processing events).

You can also set `prio_spread` to 1, which effectively disables priority spread. However, it's expected that this causes some performance penalty.

**Comment by bogdanPricope** [comment]
Great news. 
The prio_spread = 1 fixed my problem (results are consistent over multiple runs)

1 core :  2.82	|  2.82 |  2.82
2 cores:  5.61	|  5.58 |  5.51 | 5.69
3 cores: 11.23	| 11.25 | 11.26
4 cores: 14.22	| 14.23 | 14.28

odp_schedule_print() for the two case:
- prio_spread = 4:
Scheduler debug info
--------------------
  scheduler:         basic
  max groups:        29
  max priorities:    8
  num spread:        4
  prefer ratio:      64

  Number of active event queues:
              spread
                   0       1       2       3
  prio 0:-
  prio 1:-
  prio 2:-
  prio 3:-
  prio 4
    group 0:   1/  3   1/  3   3/  3   2/  2
    group 1:   0/  0   0/  0   0/  0   0/  0
    group 2:   0/  0   0/  0   0/  0   0/  0
  prio 5:-
  prio 6:-
  prio 7:-

  Number of threads:
             spread
    group 0: 3 3 3 2
    group 1: 1 1 2 0
    group 2: 2 2 1 2

- prio_spread = 1:
Scheduler debug info
--------------------
  scheduler:         basic
  max groups:        29
  max priorities:    8
  num spread:        1
  prefer ratio:      64

  Number of active event queues:
              spread
                   0
  prio 0:-
  prio 1:-
  prio 2:-
  prio 3:-
  prio 4
    group 0:   7/ 11
    group 1:   0/  0
    group 2:   0/  0
  prio 5:-
  prio 6:-
  prio 7:-

  Number of threads:
             spread
    group 0: 11
    group 1: 4
    group 2: 7

Merci,
Bogdan

**Comment by MatiasElo** [comment]
Great that this helped. If you want to tweak the application code more, one thing caught my eye. All queues are using scheduling group 0, which I assume is `ODP_SCHED_GROUP_ALL`. It could help if you use `ODP_SCHED_GROUP_WORKER` for the fast path queues.

**Comment by bogdanPricope** [comment]
Thank you Matias. I'll try it today or after the vacation.

**Comment by bogdanPricope** [comment]
Nope..  with ODP_SCHED_GROUP_WORKER (and prio_spread set to the number of workers) the results are not consistent over consecutive runs. I'll keep prio_spread = 1 for now.

Btw, Merry Christmas and thanks for the help!

**Comment by MatiasElo** [comment]
Okay, thanks for testing. Merry Christmas and Happy New Year to you as well!
