### ISSUE TITLE
API for draining a scheduled queue

### ISSUE THREAD

**Issue by bogdanPricope** [OpenDataPlane/odp-dpdk#175]
Hi,

I have a scenario where I want to destroy (odp_queue_destroy()) a scheduled queue.
The queue is created like this:
        odp_queue_param_init(&qparam);
	qparam.type = ODP_QUEUE_TYPE_SCHED;
........

	loopq_def = odp_queue_create(q_name, &qparam);

When I am trying to destroy that queue, I am getting this error:
odp_queue_basic.c:420:queue_destroy():queue "_loopq_def" not empty

and on termination:
odp_queue_basic.c:212:queue_term_global():Not destroyed queue: _loopq_def
odp_init.c:201:term_global():ODP queue term failed.

Now, I understand that 'odp_queue_deq()' cannot be used with ODP_QUEUE_TYPE_SCHED type queues and the recommendation is to use odp_schedule() instead. This is not a useful option since we can loose useful events.

There is any other method to drain this queue?

Best regards,
Bogdan

**Comment by MatiasElo** [comment]
Hi Bogdan,

When destroying a scheduled queue, it's the application's responsibility to make sure the queue is empty.

First one has to be sure that no new events are being enqueued to the particular queue (e.g. by packet input or timers). Then the application can send a "clean-up" event to the queue and when the event is received back from `odp_schedule()`, the queue (assuming atomic for simplicity) can be safely destroyed.

**Comment by bogdanPricope** [comment]
Thank you, Matias.
Not trivial to use this method, isn't it?
