### ISSUE TITLE
DPDK v20.11

### ISSUE THREAD

**Issue by bogdanPricope** [OpenDataPlane/odp-dpdk#183]
Hi,

Do you have any plan to switch to DPDK v20.11 as the recommended dpdk version?

Best regards

**Comment by MatiasElo** [comment]
Hi Bogdan,

Yes, the recommended DPDK version will be changed to 20.11 after the latest API version bump (v1.35) is merged. Support for DPDK v21.11 will also be added in near future.

**Comment by bogdanPricope** [comment]
Hi Matias,
Thank you for the answer.
