### ISSUE TITLE
Significant drop in performance beteen v1.32 and v1.34

### ISSUE THREAD

**Issue by bogdanPricope** [OpenDataPlane/odp-dpdk#184]
Hi,

I am running an UDP termination test with the following odp-dpdk configuration:

PKG_CONFIG_PATH=.......dpdk/install/lib64/pkgconfig ./configure --prefix=....../odp-dpdk_install --enable-dpdk --enable-dpdk-zero-copy --with-platform=linux-generic

I can see a significant drop of performance:
odp-dpdk v1.32 : 8.5 mpps
odp-dpdk v1.33 : 7.5 mpps
odp-dpdk v1.34 : 6.3 mpps

You are not going in the right direction.

**Comment by MatiasElo** [comment]
Hi Bogdan,

What kind of test application are you using (workers, pktio type (sched/direct))? In my testing (mainly with odp_l2fwd) I haven't noticed performance degradation.

One exception is `linux-gen: sched: update random data table` commit (795d576fb), which can cause performance changes when using scheduled pktio. However, this can be mitigated by setting `sched_basic:prio_spread` to worker count in the config file. Adjusting the number of DPDK RX/TX descriptors can also have an effect (`pktio_dpdk: num_rx_desc/num_tx_desc`)

**Comment by bogdanPricope** [comment]
Hi Matias,

I am using linux-generic platform, scheduler mode, DPDK zero-copy.

Basically, is a usecase where some traffic (UDP,  some port) is sent (classified) to a different scheduler group and then 'sent' to a control thread where is terminated (different methods, etc). It is similar to https://github.com/NetInoSoftware/nfp/blob/master/example/classifier/classifier_main.c but now it uses 'multi' packet processing API.

As I switched from DPDK 19.11 to 20.11, ODP-DPDK v1.32 to v1.34 (+ our API change) I started to see things...

**Comment by bogdanPricope** [comment]
Btw, you may need separate termination and generation tests instead of fwd. I can see weird stuff on TX, but this may be my setup...

**Comment by bogdanPricope** [comment]
Hi Matias,

DPDK version does not influence the performance (for this case).

I've re-tested with different versions (1.32 and 1.34) and different configuration files. As far as I understand the difference is given by the size of packet pool:
 - with 10240 pkts (our default) we have 8.7 mpps for v1.32 and 6.5 mpps for v1.34
 - with 262143 pkts we have ~7.6 mpps in both versions

Does this makes sense for you?

**Comment by MatiasElo** [comment]
Hi Bogdan,

Hmm, nothing obvious comes to mind. With zero-copy DPDK pktio the DPDK mempool cache size is calculated dynamically based on the packet pool size (dpdk.c: `cache_size()`), but I doubt this would cause that much difference. You could hack this function and test different cache sizes.

It would be helpful if you could profile the application with `perf` and see if there are some clear differences when using different ODP versions.

We just tagged [v1.36](https://github.com/OpenDataPlane/odp/releases/tag/v1.36.0.0). Could you please test this release?

**Comment by bogdanPricope** [comment]
Hi Matias,

From my point of view, it doesn't really matter since I am not planning to do performance tests with the default pool size.
I'll have a look at 1.36 next week when I plan some more tests. 

Thank you for your help.
