### ISSUE TITLE
Supported pktio types

### ISSUE THREAD

**Issue by bogdanPricope** [OpenDataPlane/odp-dpdk#200]
There is any ODP API that can 'tell' the pktios supported by a platform?

While different ODP platforms implement different pktio types, some pktios may be (are) shared between the platforms e.g. 'loopback' and 'null' pktios are shared between 'linux-dpdk' and 'linux-generic'.

**Comment by MatiasElo** [comment]
Hi,

There is no such API as the supported device names are highly implementation specific. However, loopback pktio should be always supported as it's defined in the API ("loop"). Now that you mentioned it, we could also add "null" pktio to the API in the same manner.

**Comment by bogdanPricope** [comment]
Hi Matias,

A 'tap' pktio supported on all platforms would be very interesting from OFP/NFP point of view: OFP uses tap interfaces for 'slow path' support and I am considering the idea be replace them with 'tap' pktios.

It would be nice to have an API that could say if 'tap' pktio is supported for a platform (to switch between implementations).

Best regards
