### ISSUE TITLE
odp classifier sample app issue

### ISSUE THREAD

**Issue by savitakulk** [OpenDataPlane/odp-dpdk#212]
We are trying to run odp_classifier sample application on VMs with the Mellanox platform and getting the following errors. Any suggestions would be helpful.
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:594]:odp_pktio_start():DBG: Inside odp_pktio_start
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:599]:odp_pktio_start():DBG: calling get_pktio_entry
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:605]:odp_pktio_start():DBG: calling lock_entry
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:614]:odp_pktio_start():DBG:calling entry->s.ops->start
mlx5_pci: port 0 empty mbuf pool
mlx5_pci: port 0 Rx queue allocation failed: Cannot allocate memory
ODP:27.12.2022(13:56:23):[ERROR]:[odp_packet_dpdk.c:1725]:dpdk_start():Device start failed: err=-12, port=0
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:623]:odp_pktio_start():DBG: res of entry->s.ops->start -1
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:625]:odp_pktio_start():DBG:calling ODP_PKTIN_MODE_SCHED
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:626]:odp_pktio_start():DBG:calling ODP_PKTIN_MODE_SCHED 1 mode 1
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:633]:odp_pktio_start():DBG:num = 1
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:644]:odp_pktio_start():DBG:calling odp_sched_fn->pktio_start
ODP:27.12.2022(13:56:23):[DEBUG]:[../linux-generic/odp_packet_io.c:650]:odp_pktio_start():interface: 0, input queues: 1, output queues: 1
odp_classifier.c:711:main():Error: unable to start pktio

-------------------------------------------------------------------------------------------------------------------------------
P.S: We are running the classifier with the following command

./odp_classifier -i 1 -m 0 -p "ODP_PMR_SIP_ADDR:10.10.10.0:0xFFFFFF00:queue1" -p "ODP_PMR_SIP_ADDR:10.10.10.10:0xFFFFFFFF:queue1:queue2"

SW Versions used:
DPDK version-dpdk-20.11.1 
odp version as -release 2.9.1 
pktio type as normal.

**Comment by MatiasElo** [comment]
Hi,

The ODP-DPDK version you shared seems invalid. The latest tagged version is `v1.39.0.0_DPDK_19.11`. I'd suggest using the latest code anyway.

The Mellanox drivers can sometimes be problematic. Can you run other sample applications which don't use classifier? For example odp_l2fwd: `$ sudo ./test/performance/odp_l2fwd -i 0 -m 1 -c 1`

If not, have you tried running native DPDK examples (e.g l2fwd)?

**Comment by savitakulk** [comment]
Hi, native DPDK application works fine on the same platform. L2 forward sample app ->"l2fwd" is also working fine.
------------------------------------------------------------
# ./odp_l2fwd -i 0 -m 1 -c 1
ODP:10.01.2023(12:25:09):[DEBUG]:[odp_init.c:117]:_odp_init_dpdk():_odp_init_dpdk
ODP:10.01.2023(12:25:09):[DEBUG]:[odp_init.c:142]:_odp_init_dpdk():arg[0]: odpdpdk
ODP:10.01.2023(12:25:09):[DEBUG]:[odp_init.c:172]:_odp_init_dpdk():0:0000:06:00.0
ODP:10.01.2023(12:25:09):[DEBUG]:[odp_init.c:172]:_odp_init_dpdk():1:0000:07:00.0
ODP:10.01.2023(12:25:09):[DEBUG]:[odp_init.c:172]:_odp_init_dpdk():2:0000:09:00.0
ODP:10.01.2023(12:25:09):[DEBUG]:[odp_init.c:176]:_odp_init_dpdk():3 PCIE VF's detected
ODP:10.01.2023(12:25:09):[DEBUG]:[odp_init.c:195]:_odp_init_dpdk():rte_devargs_add: 0000:06:00.0,rx_vec_en=0,mprq_en=0 done
ODP:10.01.2023(12:25:09):[DEBUG]:[odp_init.c:195]:_odp_init_dpdk():rte_devargs_add: 0000:07:00.0,rx_vec_en=0,mprq_en=0 done
ODP:10.01.2023(12:25:09):[DEBUG]:[odp_init.c:195]:_odp_init_dpdk():rte_devargs_add: 0000:09:00.0,rx_vec_en=0,mprq_en=0 done
EAL: Detected 6 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL:   Invalid NUMA socket, default to 0
EAL: Probe PCI driver: mlx5_pci (15b3:101e) device: 0000:06:00.0 (socket 0)
common_mlx5: RTE_MEM is selected.
mlx5_pci: Size 0xFFFF is not power of 2, will be aligned to 0x10000.
EAL:   Invalid NUMA socket, default to 0
EAL: Probe PCI driver: mlx5_pci (15b3:101e) device: 0000:07:00.0 (socket 0)
mlx5_pci: Size 0xFFFF is not power of 2, will be aligned to 0x10000.
EAL:   Invalid NUMA socket, default to 0
EAL: Probe PCI driver: mlx5_pci (15b3:101e) device: 0000:09:00.0 (socket 0)
mlx5_pci: Size 0xFFFF is not power of 2, will be aligned to 0x10000.
EAL: No legacy callbacks, legacy socket not created
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_init.c:234]:_odp_init_dpdk():rte_eal_init OK
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_system_info.c:106]:default_huge_page_size():defaut hp size is 2048 kB
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_system_info.c:106]:default_huge_page_size():defaut hp size is 2048 kB
Pool config:
  pool.pkt.max_num: 262143

ODP:10.01.2023(12:25:10):[DEBUG]:[odp_pool.c:177]:_odp_pool_init_global():
Pool init global
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_pool.c:178]:_odp_pool_init_global():  odp_buffer_hdr_t size:       192
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_pool.c:179]:_odp_pool_init_global():  odp_packet_hdr_t size:       448
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_pool.c:180]:_odp_pool_init_global():  odp_timeout_hdr_t size:      256
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_pool.c:181]:_odp_pool_init_global():  odp_event_vector_hdr_t size: 256
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_pool.c:183]:_odp_pool_init_global():
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_queue_basic.c:124]:queue_init_global():Starts...
Queue config:
  queue_basic.max_queue_size: 8191
  queue_basic.default_queue_size: 4095

ODP:10.01.2023(12:25:10):[DEBUG]:[../linux-generic/odp_queue_lf.c:314]:_odp_queue_lf_init_global():
Lock-free queue init
ODP:10.01.2023(12:25:10):[DEBUG]:[../linux-generic/odp_queue_lf.c:315]:_odp_queue_lf_init_global():  u128 lock-free: 0

ODP:10.01.2023(12:25:10):[DEBUG]:[odp_queue_basic.c:166]:queue_init_global():... done.
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_queue_basic.c:167]:queue_init_global():  queue_entry_t size 256
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_queue_basic.c:168]:queue_init_global():  max num queues     2048
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_queue_basic.c:169]:queue_init_global():  max queue size     8191
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_queue_basic.c:170]:queue_init_global():  max num lockfree   0
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_queue_basic.c:171]:queue_init_global():  max lockfree size  0

Using scheduler 'basic'
ODP:10.01.2023(12:25:10):[DEBUG]:[../linux-generic/odp_schedule_basic.c:403]:schedule_init_global():Schedule init ... Scheduler config:
  sched_basic.prio_spread: 4
  sched_basic.prio_spread_weight: 63
  sched_basic.burst_size_default[] =  32  32  32  32  32  16   8   4
  sched_basic.burst_size_max[] =     255 255 255 255 255  16  16   8
  sched_basic.group_enable.all: 1
  sched_basic.group_enable.worker: 1
  sched_basic.group_enable.control: 1

ODP:10.01.2023(12:25:10):[DEBUG]:[../linux-generic/odp_schedule_basic.c:458]:schedule_init_global():done
Packet IO config:
  pktio.pktin_frame_offset: 0

PKTIO: initialized null interface.

ODP crypto is DISABLED

ODP compress is DISABLED

ODP traffic manager is DISABLED

ODP IPSec is DISABLED

ODP system info
---------------
ODP API version:  1.25.2
ODP impl name:    odp-dpdk
ODP impl details: odp-dpdk 1.25.2-0 (v1.25.2) 1.25.2.0
DPDK version:     20.11.1
CPU model:        Intel Xeon Processor (Cascadelake)

CPU freq (hz):    2992945000
Cache line size:  64
CPU count:        5
CPU mask:         0x3E


CPU features supported:
SSE3 PCLMULQDQ VMX SSSE3 FMA CMPXCHG16B PCID SSE4_1 SSE4_2 X2APIC MOVBE POPCNT TSC_DEADLINE AES XSAVE OSXSAVE AVX F16C RDRAND FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH MMX FXSR SSE SSE2 SS ARAT FSGSBASE AVX2 BMI2 ERMS INVPCID AVX512F LAHF_SAHF SYSCALL XD 1GB_PG RDTSCP EM64T

CPU features NOT supported:
DTES64 MONITOR DS_CPL SMX EIST TM2 CNXT_ID XTPR PDCM DCA PSN DS ACPI HTT TM PBE DIGTEMP TRBOBST PLN ECMD PTM MPERF_APERF_MSR ACNT2 ENERGY_EFF BMI1 HLE SMEP RTM LZCNT INVTSC


odp_l2fwd options
-----------------
IF-count:           1
Using IFs:          0
Mode:               PKTIN_SCHED_PARALLEL, PKTOUT_DIRECT
Promisc mode:       disabled
Burst size:         32
Number of pools:    1
Num worker threads: 1
First CPU:          5
CPU mask:           0x20
Packets per pool:   16384
Packet length:      1536


ODP:10.01.2023(12:25:10):[DEBUG]:[odp_pool.c:681]:odp_pool_create():type: packet, name: packet pool, num: 16384, len: 1536, blk_size: 1664, uarea_size: 0, hdr_size: 448
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_pool.c:720]:odp_pool_create():Metadata size: 448, mb_size 2112
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_pool.c:544]:calc_cache_size():Cache_size: 512
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_pool.c:769]:odp_pool_create():Header/element/trailer size: 64/2112/64, total pool size: 36700160
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_packet_dpdk.c:652]:dpdk_init_capability():
 #HW Device dpdk_port_id 0 rx_offload_capa 0x0000000000186a1f
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_packet_dpdk.c:653]:dpdk_init_capability():
 #HW Device dpdk_port_id 0 tx_offload_capa 0x00000000000096af
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_packet_dpdk.c:261]:init_options():DPDK interface (mlx5_pci): 0
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_packet_dpdk.c:262]:init_options():  multicast:   1
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_packet_dpdk.c:263]:init_options():  num_rx_desc: 2048
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_packet_dpdk.c:264]:init_options():  num_tx_desc: 2048
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_packet_dpdk.c:265]:init_options():  rx_drop_en:  0
ODP:10.01.2023(12:25:10):[DEBUG]:[odp_packet_dpdk.c:408]:_dpdk_print_port_mac():Port 0, MAC address: BE:6E:93:D9:0B:DD
ODP:10.01.2023(12:25:10):[DEBUG]:[../linux-generic/odp_packet_io.c:411]:odp_pktio_open():interface: 0, driver: odp-dpdk
created pktio 1, dev: 0, drv: odp-dpdk
created 1 input and 1 output queues on (0)

Queue binding (indexes)
-----------------------
worker 0
  tx: pktio 0, queue 0

[01] PKTIN_SCHED_PARALLEL, PKTOUT_DIRECT

dpdk_start PORT ID received 0
Calling generate_gtp_dst_l2_ipv4_ipv4
Calling generate_gtp_dst_l2_ipv4_ipv6
Calling generate_gtp_dst_l2_ipv6_ipv4
Calling generate_gtp_dst_l2_ipv6_ipv6
Calling generate_gtp_src_l2_ipv4_ipv4
Calling generate_gtp_src_l2_ipv4_ipv6
Calling generate_gtp_src_l2_ipv6_ipv4
Calling generate_gtp_src_l2_ipv6_ipv6
ODP:10.01.2023(12:25:11):[DEBUG]:[odp_packet_dpdk.c:945]:dpdk_ptype_support_set():  supported ptype: 0x1
ODP:10.01.2023(12:25:11):[DEBUG]:[odp_packet_dpdk.c:945]:dpdk_ptype_support_set():  supported ptype: 0x90
ODP:10.01.2023(12:25:11):[DEBUG]:[odp_packet_dpdk.c:945]:dpdk_ptype_support_set():  supported ptype: 0xe0
ODP:10.01.2023(12:25:11):[DEBUG]:[odp_packet_dpdk.c:945]:dpdk_ptype_support_set():  supported ptype: 0x600
ODP:10.01.2023(12:25:11):[DEBUG]:[odp_packet_dpdk.c:945]:dpdk_ptype_support_set():  supported ptype: 0x300
ODP:10.01.2023(12:25:11):[DEBUG]:[odp_packet_dpdk.c:945]:dpdk_ptype_support_set():  supported ptype: 0x100
ODP:10.01.2023(12:25:11):[DEBUG]:[odp_packet_dpdk.c:945]:dpdk_ptype_support_set():  supported ptype: 0x200
ODP:10.01.2023(12:25:11):[DEBUG]:[../linux-generic/odp_packet_io.c:650]:odp_pktio_start():interface: 0, input queues: 1, output queues: 1
0 pps, 0 max pps, 0 rx drops, 0 tx drops
0 pps, 0 max pps, 0 rx drops, 0 tx drops
0 pps, 0 max pps, 0 rx drops, 0 tx drops

**Comment by MatiasElo** [comment]
Thanks for the logs. My first guess is that the packet pool used by odp_classifier example is too small for mlx5 driver.

Please update to the latest odp-dpdk release (v1.39.0.0_DPDK_19.11), which includes an updated version of this application. In that version the default pool size has been increased to 10K and there is also a new `-s` option for adjusting pool size.

**Comment by savitakulk** [comment]
With v1.39.0.0_DPDK_19.11 the odp classifier sample application works fine. Thanks for your input.
