### ISSUE TITLE
odp classifier PMR limits -query

### ISSUE THREAD

**Issue by savitakulk** [OpenDataPlane/odp-dpdk#214]
Hi,
We are testing the odp classifier sample application with version-v1.39.0.0_DPDK_19.11.

With v1.39.0.0_DPDK_19.11 the odp classifier and scheduler:-

we are seeing the following capabilities.

 CLASSIFIER
    supported_terms:      0x1bffff
    max_pmr_terms:        256
    available_pmr_terms:  256
    max_cos:              64
    max_hash_queues:      32
    hash_protocols:       0x3f
    pmr_range_supported:  0
    max_mark:             65535
    stats.queue:          0x6

  SCHEDULER
    max_ordered_locks:    2
    max_groups:           61
    max_prios:            8
    max_queues:           1023
    max_queue_size:       8191
    max_flow_id:          255
    lockfree_queues:      not supported
    waitfree_queues:      not supported
===================================================

Q1.As max PMR per PKTIO is defined as 8.Is this the actual limitation of the classifier that we can't go beyond 8PMRs
per PKTIO?

 /* Maximum PMRs attached in PKTIO Level */
 #define CLS_PMR_PER_COS_MAX             8

Q2.Whether scheduler wise only 8 priorities are supported? Any chance of getting more prios supported in the next version of ODP?
of ODP?

Q3.We are seeing the following structure defined in the ODP code

typedef struct odp_pmr_param_t {
        /** Packet Matching Rule term */
        odp_cls_pmr_term_t  term;

        /** True if the value is range and false if match. Default is false. */
        odp_bool_t range_term;

        /** Variant mappings for types of matches */
        union {
                /** Parameters for single-valued matches */
                struct {
                        /** Points to the value to be matched. Value size and
                         *  endianness are defined by the term used. Values of
                         *  protocol fields are defined in big endian format.
                         */
                        const void *value;
                        /** Mask of the bits to be matched. The same size and
                         *  endianness is used than with the value. */
                        const void *mask;
                } match;

                /** Parameter for range value matches */
                struct {
                        /** Start value of the range */
                        const void *val_start;

                        /** End value of the range */
                        const void *val_end;
                } range;
        };

Whether range value checks are supported in the PMRs used in the present version of ODP?

**Comment by MatiasElo** [comment]
Hi,

Q1) Looks like this is the current limit for a single CoS. @JereLeppanen can comment more, since he's more familiar with the classifier code. 

Q2) The number of priorities is critical for software scheduler performance (more priorities -> more scheduling overhead), so it's unlikely that we'd increase the default number of priorities. However, it's possible that we could make it easier to configure. Today, you can increase the number of priorities like this:
```
diff --git a/config/odp-linux-dpdk.conf b/config/odp-linux-dpdk.conf
index d28f728f2..1261e1a70 100644
--- a/config/odp-linux-dpdk.conf
+++ b/config/odp-linux-dpdk.conf
@@ -166,18 +166,18 @@ sched_basic: {
        # Large burst sizes improve throughput, but decrease application
        # responsiveness to higher priority events due to head of line blocking
        # caused by a burst of lower priority events.
-       burst_size_default = [ 32,  32,  32,  32,  32, 16,  8, 4]
-       burst_size_max     = [255, 255, 255, 255, 255, 16, 16, 8]
+       burst_size_default = [ 32,  32,  32,  32,  32, 16,  8, 4, 4, 4]
+       burst_size_max     = [255, 255, 255, 255, 255, 16, 16, 8, 8, 8]
 
        # Burst size configuration per priority for each scheduled queue type.
        # Overrides default values set in 'burst_size_default' and
        # 'burst_size_max' if != 0.
-       burst_size_parallel     = [0, 0, 0, 0, 0, 0, 0, 0]
-       burst_size_max_parallel = [0, 0, 0, 0, 0, 0, 0, 0]
-       burst_size_atomic       = [0, 0, 0, 0, 0, 0, 0, 0]
-       burst_size_max_atomic   = [0, 0, 0, 0, 0, 0, 0, 0]
-       burst_size_ordered      = [0, 0, 0, 0, 0, 0, 0, 0]
-       burst_size_max_ordered  = [0, 0, 0, 0, 0, 0, 0, 0]
+       burst_size_parallel     = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
+       burst_size_max_parallel = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
+       burst_size_atomic       = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
+       burst_size_max_atomic   = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
+       burst_size_ordered      = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
+       burst_size_max_ordered  = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 
        # Automatically updated schedule groups
        #
diff --git a/platform/linux-generic/odp_schedule_basic.c b/platform/linux-generic/odp_schedule_basic.c
index 594360326..c31091ab4 100644
--- a/platform/linux-generic/odp_schedule_basic.c
+++ b/platform/linux-generic/odp_schedule_basic.c
@@ -46,7 +46,7 @@
 #define NO_SYNC_CONTEXT ODP_SCHED_SYNC_PARALLEL
 
 /* Number of priority levels  */
-#define NUM_PRIO 8
+#define NUM_PRIO 10
 
 /* Group mask (prio_grp_mask) size in bits */
 #define GRP_MASK_BITS 64
```

Q3) `odp_cls_capability()` function can be used to check classifier capabilities. Range value matches are currently not supported by the implementation.

**Comment by JereLeppanen** [comment]
Q1) Looks like the comment `/* Maximum PMRs attached in PKTIO Level */` is outdated and incorrect. That comment wasn't updated when the limit was changed to a per CoS limit. CLS_PMR_PER_COS_MAX is the per CoS limit, and `odp_cls_capability()` returns the total limit in the `max_pmr_terms` member of `odp_cls_capability_t`.

**Comment by savitakulk** [comment]
Thanks a lot for the clarifications regrading->
Q1)Limit wise there is no constraint on PKTIO but per COS max 8PMRs are supported is it?
 
Per COS it's mentioned 8 PMRs(CLS_PMR_PER_COS_MAX-8) ,but per PKTIO how many COSs can be supported.

capability says -64[#define CLS_COS_MAX_ENTRY 64]  is it across all PKTIOs or per PKTIO? what is the system level -number of PMRs this ODP classifier can support?

Q4)how we can define the order of PMRs in ODP?If we need some PMRs based on SIP/DIP and some based on custom L3 fields?
Which ODP API ensures that SIP/DIP based PMRs will be executed first and then custom L3 based PMRs?

**Comment by JereLeppanen** [comment]
> Q1)Limit wise there is no constraint on PKTIO but per COS max 8PMRs are supported is it?

Yes, that's right. 8 PMRs per CoS, no limit per pktio.

> Per COS it's mentioned 8 PMRs(CLS_PMR_PER_COS_MAX-8) ,but per PKTIO how many COSs can be supported.
> capability says -64[#define CLS_COS_MAX_ENTRY 64] is it across all PKTIOs or per PKTIO?

Across all pktios. The capability (max_cos) indicates the total limit (per ODP instance), which is CLS_COS_MAX_ENTRY, or 64.

> what is the system level -number of PMRs this ODP classifier can support?

That's the max_pmr_terms capability, which is CLS_PMR_MAX_ENTRY, or 256.

**Comment by savitakulk** [comment]
> > Q1)Limit wise there is no constraint on PKTIO but per COS max 8PMRs are supported is it?
> 
> Yes, that's right. 8 PMRs per CoS, no limit per pktio.
> 
> > Per COS it's mentioned 8 PMRs(CLS_PMR_PER_COS_MAX-8) ,but per PKTIO how many COSs can be supported.
> > capability says -64[#define CLS_COS_MAX_ENTRY 64] is it across all PKTIOs or per PKTIO?
> 
> Across all pktios. The capability (max_cos) indicates the total limit (per ODP instance), which is CLS_COS_MAX_ENTRY, or 64.
> 
> > what is the system level -number of PMRs this ODP classifier can support?
> 
> That's the max_pmr_terms capability, which is CLS_PMR_MAX_ENTRY, or 256.

**Comment by savitakulk** [comment]
So system level max_pmr_terms supported are 256 with 256 destination ODP queues, which can be assigned while adding the PMRs.Is this the correct understanding?Or we can assign same odp queue also to multiple PMRs ex.2PMRs with Q1,next 2PMRs with Q2..?Is there any restriction like queues assigned to PMRs should be unique?

**Comment by savitakulk** [comment]
Thanks a lot for the clarification -In PMR ,Range value matching whether any upcoming version of ODP will be supporting?

**Comment by JereLeppanen** [comment]
> So system level max_pmr_terms supported are 256 with 256 destination ODP queues, which can be assigned while adding the PMRs.Is this the correct understanding?

Basically yes, but more accurately the queue is assigned to a CoS, and the CoS is then assigned to the PMR.

> Or we can assign same odp queue also to multiple PMRs ex.2PMRs with Q1,next 2PMRs with Q2..?Is there any restriction like queues assigned to PMRs should be unique?

No restrictions. The same queue can be assigned to multiple CoSes, and the same CoS can be assigned to multiple PMRs.

**Comment by JereLeppanen** [comment]
> In PMR ,Range value matching whether any upcoming version of ODP will be supporting?

We currently have no plans regarding this. Contributions (to the main repository https://github.com/OpenDataPlane/odp) would be much appreciated.

**Comment by savitakulk** [comment]
ok, thanks a lot for your inputs.
