### ISSUE TITLE
Implication of changing CLS_PMR_PER_COS_MAX

### ISSUE THREAD

**Issue by sugandha7** [OpenDataPlane/odp-dpdk#221]
I had changed CLS_PMR_PER_COS_MAX from 8 to 16 for supporting more COS per PKTIO. Will it have any impact on system level performance?

**Comment by sugandha7** [comment]
Whether CLS_PMR_PER_COS_MAX should be fixed to 8 only or if we can increase this based on our requirement?
Or how does it impact the overall ODP_CLASSIFIER functionality? Kindly provide your inputs/suggestions on this.

**Comment by TuomasTaipale** [comment]
Hello Sugandha,

yes, you should be able to increase the value. It will have some effect on classification latencies as linear searches will be done on a slightly longer array. You can use, e.g., the classifier tester provided by ODP (`odp_classifier`, example/classifier/odp_classifier.c) to check how the performance varies with different values.
