### ISSUE TITLE
asymmetric queue for pktio

### ISSUE THREAD

**Issue by savitakulk** [OpenDataPlane/odp-dpdk#226]
Hi, In case of ODP Pktio-whether number of input ODP queues must be equal to number of out queues?Or ODP side there won't be any issue if we are going ahead with configuration of "NUMBER_TX_QUEUES per PKTIO > NUMBER_RX_QUEUES per PKTIO through which we might be receiving/transmitting the packets."(keeping pktio_param.in_mode = ODP_PKTIN_MODE_DIRECT;
  pktio_param.out_mode = ODP_PKTOUT_MODE_DIRECT;
)

**Comment by TuomasTaipale** [comment]
Hello @savitakulk,

using asymmetric queue count for input and output should not be an issue. Note that `odp_pktio_capability_t::max_input_queues`/`max_output_queues` will affect how many queues one can maximally configure per direction.

**Comment by savitakulk** [comment]
Thanks a lot for the clarification and input on the queue configurations
per pktio.

Regards,
