### ISSUE TITLE
libodp-dpdk.so won't copy to installation directory

### ISSUE THREAD

**Issue by LinArcX** [OpenDataPlane/odp-dpdk#234]
I tried to build ofp using dpdk and odp-dpdk. dpdk and odp-dpdk were successfully built like this:
```
git clone https://github.com/DPDK/dpdk
pushd dpdk
git checkout v22.11
PKG_CONFIG_LIBDIR=/usr/lib/i386-linux-gnu/pkgconfig meson setup -Dc_args='-m32' -Dc_link_args='-m32' -Dexamples=all build
pushd build
ninja
sudo meson install
sudo ldconfig
popd
popd
```
And
```
git clone https://github.com/OpenDataPlane/odp-dpdk
pushd odp-dpdk
./bootstrap
PKG_CONFIG_PATH=/usr/local/lib/x86_64-linux-gnu/pkgconfig ./configure --enable-dpdk --build=i386-linux-gnu "CFLAGS=-m32" "CXXFLAGS=-m32" "LDFLAGS=-m32"
make -j4
make install
popd
```
But when I try to build ofp like this:
```
git clone https://github.com/OpenFastPath/ofp
pushd ofp
./bootstrap
PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig ./configure --build=i386-linux-gnu --with-odp=/usr/local/lib --with-odp-lib=odp-dpdk "CFLAGS=-m32" "CXXFLAGS=-m32" "LDFLAGS=-m32"
make -j4
make install
popd
```
It gives me this error:
```
checking for libodp-dpdk >= 1.35.0.0... no
configure: error: Package requirements (libodp-dpdk >= 1.35.0.0) were not met:

No package 'libodp-dpdk' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ODP_CFLAGS
and ODP_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
Seems that ofp can't find libodp-dpdk library and that's true. I searched in `/usr/local/lib/x86_64-linux-gnu` and `/usr/lib/x86_64-linux-gnu`. there is no `libodp-dpdk` there. 

But I found them in odp-dpdk source directory after I built the  source code: `odp-dpdk/lib/.libs/libodp-dpdk.so`

Why they didn't copy to system-level directories? And how to fix this issue?

**Comment by MatiasElo** [comment]
Did you have correct access rights to install the library? You can also use `--prefix` option to select a custom ODP install directory. The custom install directory can then be passed to OFP with `with-odp` option.

E.g. `./configure  --with-odp-lib=odp-dpdk --with-odp=<install_path>`
