### ISSUE TITLE
Run-Time Hierarchy Updates

### ISSUE THREAD

**Issue by savitakulk** [OpenDataPlane/odp-dpdk#236]
Hi,

Whether ODP-TM supports dynamic hierarchy updates for creation and deletion of TM nodes/queues. Basically whether ODP-TM supports for on-the-fly changes to the scheduling hierarchy?

**Comment by JannePeltonen** [comment]
ODP API has dynamic_topology_update TM capability flag. The TM implementation in linux-generic ODP and in ODP-DPDK sets the flag, so it at least claims to support dynamic topology updates. There are also other similar capability flags, including dynamic_shaper_update, which are also set by that TM implementation. I do not know how well the dynamic updates have been tested to work, though.

**Comment by savitakulk** [comment]
Thanks a lot for the clarification/input.
