### ISSUE TITLE
How to compile DPDK for MIPS architecture ??

### ISSUE THREAD

**Issue by speedlong2008** [OpenDataPlane/odp-dpdk#57]

**Comment by Bill-Fischofer-Linaro** [comment]
Hi @speedlong2008 can you give a give more detail about your project and the issues you're running into? MIPS in theory is supported but we don't have access to MIPS-based equipment so odp-dpdk is currently only tested on x86 and Armv8 processors.

**Comment by 90geek** [comment]
I did not find the configuration problem of mips. so, I do not knew how to do Compile. I used loongson chip.
