### ISSUE TITLE
configure fails for odp, odp-dpdk on fedora 29 when checking for atomic_exchange_16

### ISSUE THREAD

**Issue by trozet** [OpenDataPlane/odp-dpdk#68]
When trying to ./configure either odp or odp-dpdk (also tried the OFP automatic install script), I get:

checking for GCC atomic builtins... yes
checking whether -latomic is needed for 64-bit atomic built-ins... no
checking for __int128... yes
checking whether -latomic is needed for 128-bit atomic built-ins... yes
checking for __atomic_exchange_16 in -latomic... no
configure: error: in `/usr/src/odp-dpdk':
configure: error: __atomic_exchange_16 is not available

I'm running on x86_64 with gcc version 8.2.1 20181215 (Red Hat 8.2.1-6) (GCC)

**Comment by matiaselo** [comment]
Do you have libatomic installed?

**Comment by trozet** [comment]
Now I feel like an idiot :) No I missed that in the DEPENDENCIES file. Thanks for your help. It may be good to add in the web instructions to install required packages in that file:
https://openfastpath.org/index.php/service/download/
