### ISSUE TITLE
LAG support in ODP

### ISSUE THREAD

**Issue by Neetika02** [OpenDataPlane/odp-dpdk#99]
Hello,

Are LAGs(Link Access Group) supported in ODP.
If yes how to use the same. I understand we can create pktio interface per Port. 

Regards,
Neetika

**Comment by matiaselo** [comment]
Hi Neetika,

Sorry for slow reply, just came back from vacation. ODP doesn't currently have support for LAG, but you should be able to use DPDK link bonding poll mode driver transparently with ODP-DPDK.

You can pass the required EAL command line parameters using ODP_PLATFORM_PARAMS environment variable.
E.g. `ODP_PLATFORM_PARAMS="--vdev 'net_bonding0,bond_opt0=...,bond opt1=...'"`
